baseURL = 'https://feelstart.github.io'
languageCode = ' zh_CN'
title = '加蛋加葱花～'
theme = "FixIt"
defaultContentLanguage = 'zh-cn'


[params]
  [params.author]
    name = "加蛋加葱花～"
    email = "1242959598@qq.com"
    link = ""
    avatar = ""
